disco-timeline/config/routes.rb
Rails.application.routes.draw do

use_doorkeeper
root 'timeline#index'

#users
  get 'register' => 'users#new', as: :new_user
  post 'users' => 'users#create', as: :create_user
  get 'users' => 'users#index', as: :users
  get 'users/:id' => 'users#show_profile', as: :user

  get 'api/me' => 'api/me#me', as: :me

#Sessions
  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete', as: :end_session
  get 'sign_out' => 'sessions#delete', as: :sign_out

  #events
    post 'events' => 'events#create'
    get 'events/new' => 'events#new', as: :new_event
    get 'events/:id' => 'events#show', as: :event
    get 'events/:id/edit' => 'events#edit', as: :edit_event
    delete 'events/:id' => 'events#delete'
    patch 'events/:id' => 'events#update'

#api_events

  get 'api/events/new' => 'api/events#new'
  post 'api/events' => 'api/events#create'
  get 'api/events' => 'api/events#index'
  get 'api/events/:id' => 'api/events#show'
  patch 'api/events/:id' => 'api/events#update'
  put 'api/events/:id' => 'api/events#update'
  delete 'api/events/:id' => 'api/events#delete'

#api users
post 'api/registrations' => 'api/registrations#create'


end

disco-timeline/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

disco-timeline/app/models/event.rb
class Event < ApplicationRecord
end

disco-timeline/app/models/user.rb
class User < ApplicationRecord
  # validates: :username, presence: true, uniqueness: true
  has_secure_password
end

disco-timeline/app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  # before_action :doorkeeper_authorize!

  before_action do
    request.format = :json
  end

  protect_from_forgery with: :null_session

  def new
    @event = Event.new
  end

  def create
    @event = Event.new
    @event.headline = params[:event][:headline]
    @event.text = params[:event][:text]
    @event.year = params[:event][:year]
    @event.month = params[:event][:month]
    @event.day = params[:event][:day]
    @event.hour = params[:event][:hour]
    @event.minute = params[:event][:minute]
    @event.caption = params[:event][:caption]
    @event.credit = params[:event][:credit]
    @event.thumbnail = params[:event][:thumbnail]
    if @event.save
        redirect_to root_path, notice: "Event Added!"
    else render :new
  end
end

  def index
    @events= Event.all
  end

  def show
    @event = Event.find_by id: params[:id]
  end

  def update
   @event = Event.find_by id: params[:id]
   @event.headline = params[:event][:headline]
   @event.text = params[:event][:text]
   @event.year = params[:event][:year]
   @event.month = params[:event][:month]
   @event.day = params[:event][:day]
   @event.hour = params[:event][:hour]
   @event.minute = params[:event][:minute]
   @event.caption = params[:event][:caption]
   @event.credit = params[:event][:credit]
   @event.thumbnail = params[:event][:thumbnail]

     if @event.save
       render :show, status: 200 #created
     else
       render json: {errors: @event.errors}, status: 422 #error
     end
   end

 def delete
   @event = Event.find_by id: params[:id]
   @event.destroy
   render json: {ok: true}, status: 200
 end

end

disco-timeline/app/controllers/api/me_controller.rb
class Api::MeController < Api::V1::ApiController
  before_action :doorkeeper_authorize!

  # GET /me.json
  def me
   render json: current_resource_owner
  end

  private

  # Find the user that owns the access token
  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

disco-timeline/app/controllers/api/registrations_controller.rb
class Api::RegistrationsController < ApplicationController
  protect_from_forgery with: :null_session
  def create
    @user = User.new params.require(:user).permit(:username, :password)
    if @user.save
      #render api/registrations/user.json.jbuilder
      render :user
    else
      render json: @user.errors, status: 422
    end
  end
end

disco-timeline/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action do
      @current_user = User.find_by id: session[:user_id]
  end
end

disco-timeline/app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action except: :show do
    if @current_user.nil?
      redirect_to sign_in_path, alert: "Please Sign In"
    end
  end

  def show
    @event = Event.find_by id: params[:id]
  end

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new
    @event.headline = params[:event][:headline]
    @event.text = params[:event][:text]
    @event.year = params[:event][:year]
    @event.month = params[:event][:month]
    @event.day = params[:event][:day]
    @event.hour = params[:event][:hour]
    @event.minute = params[:event][:minute]
    @event.caption = params[:event][:caption]
    @event.credit = params[:event][:credit]
    @event.url = params[:event][:url]
    @event.thumbnail = params[:event][:thumbnail]

    if @event.save
      redirect_to root_path, notice: "Event Added"
      else
        render :new
      end
  end

  def edit
    @event = @current_user.events.find_by! id: params[:id]
  end

  def update
    @event = @current_user.events.find_by! id: params[:id]
    @event.headline = params[:event][:headline]
    @event.text = params[:event][:text]
    @event.year = params[:event][:year]
    @event.month = params[:event][:month]
    @event.day = params[:event][:day]
    @event.hour = params[:event][:hour]
    @event.minute = params[:event][:minute]
    @event.caption = params[:event][:caption]
    @event.credit = params[:event][:credit]
    @event.url = params[:event][:url]
    @event.thumbnail = params[:event][:thumbnail]
    if @event.save
      redirect_to root_path, notice: "Event Updated!"
    else
      render :edit
    end
  end

  def delete
    @event = @current_user.events.find_by! id: params[:id]
    @event.destroy
    redirect_to root_path, notice: "Event Deleted"
  end
end

disco-timeline/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by username: params[:username]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Signed in!"
    else
      flash.now[:alert] = "Something is wrong with your username and/or password"
      render :new
    end
  end

  def delete
    session.delete :user_id
    redirect_to root_path, notice: "Signed Out!"
  end
end

disco-timeline/app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  before_action except: :show do
    if @current_user.nil?
      redirect_to sign_in_path, alert: "Please Sign In"
    end
  end

  def index
  end
end

disco-timeline/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
     @user = User.new
     @user.email = params[:user][:email]
     @user.username = params[:user][:username]
     @user.password = params[:user][:password]
       @user.password_confirmation = params[:user][:password_confirmation]
     if @user.save
       # also sign them in
       session[:user_id] = @user.id
       redirect_to root_path, notice: "Welcome!"
     else
       render :new
     end
   end

end

disco-timeline/app/helpers/api/events_helper.rb
module Api::EventsHelper
end

disco-timeline/app/helpers/api/me_helper.rb
module Api::MeHelper
end

disco-timeline/app/helpers/api/registrations_helper.rb
module Api::RegistrationsHelper
end

disco-timeline/app/helpers/application_helper.rb
module ApplicationHelper
end

disco-timeline/app/helpers/events_helper.rb
module EventsHelper
end

disco-timeline/app/helpers/sessions_helper.rb
module SessionsHelper
end

disco-timeline/app/helpers/timeline_helper.rb
module TimelineHelper
end

disco-timeline/app/helpers/users_helper.rb
module UsersHelper
end

disco-timeline/app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @event.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

<div class="well">

<%= form_for @event do |f| %>
  <div class="form-group">
    <%= f.label :headline %>
    <%= f.text_field :headline, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :month %>
    <%= f.text_field :month, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :day %>
    <%= f.text_field :day, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :hour %>
    <%= f.text_field :hour, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :minute %>
    <%= f.text_field :minute, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_field :caption, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :thumbnail %>
    <%= f.text_field :thumbnail, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :credit %>
    <%= f.text_field :credit, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-lg btn-primary"%>
  </div>
<% end %>
</div>

disco-timeline/app/views/events/edit.html.erb
<div class="page-header">
  <h1>Update Event Details</h1>
</div>

<%= render partial: 'form' %>

disco-timeline/app/views/events/new.html.erb
<div class="page-header">
  <h1>Add Event</h1>
</div>
<%= render partial: 'form' %>

disco-timeline/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiscoTimeline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if @current_user%>
      <div class="nav">
        <ul>
          <li><%=link_to 'Sign Out', sign_out_path%></li>
          <li><%=link_to 'Add Event', new_event_path%></li>
        </ul>
      </div>
      <%else%>
      <div class="nav">
        <ul>
          <li><%=link_to 'Sign In', sign_in_path%></li>
          <li><%=link_to 'Sign Up', new_user_path%></li>
        </ul>
      </div>
    <%end%>
    <%= yield %>
  </body>
</html>

disco-timeline/app/views/timeline/index.html.erb
<div class="container">
    <header>
      <h1>Swift Discovery</h1>
    </header>
</div>

  <div id="timeline-embed">
   <div id="timeline"></div>
 </div>
 <link rel="stylesheet" href="//cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
 <link rel="stylesheet" href="//cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
 <script type="text/javascript" src="//cdn.knightlab.com/libs/timeline3/latest/js/timeline-min.js"></script>
 <script>
   $(document).ready(function(){
       var embed = document.getElementById('timeline-embed');
       embed.style.height = getComputedStyle(document.body).height;
       window.timeline = new TL.Timeline('timeline-embed', '/api/events.json', { hash_bookmark: false});
       window.addEventListener('resize', function() {
         var embed = document.getElementById('timeline-embed');
         embed.style.height = getComputedStyle(document.body).height;
         timeline.updateDisplay();
       })
     });
 </script>

</div>

disco-timeline/app/views/users/new.html.erb
<div class="container">
  <div class="thumbnail">
    <h1>Create A New Account</h1>

    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |error| %>
        <p class="alert alert-danger"><strong><%= error %></strong></p>
      <% end %>
    <% end %>

    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
      </div>

  
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, size: "60x12", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, size: "60x12", class: "form-control" %>
      </div>


      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        or
        <%= link_to "Sign In", sign_in_path %>
      </div>
    <% end %>

  </div>
</div>